name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extraer motor de audio
        run: unzip LyraProject.zip -d .

      - name: Inyectar estructura faltante (Estrategia AEGIS)
        run: |
          echo "include ':app'" > settings.gradle
          echo "buildscript { repositories { google(); mavenCentral() }; dependencies { classpath 'com.android.tools.build:gradle:7.4.2' } }" > build.gradle
          echo "allprojects { repositories { google(); mavenCentral() } }" >> build.gradle

      - name: Configurar JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Compilación Maestra (Gradle System)
        run: gradle assembleDebug

      - name: Entrega de Artefacto (APK)
        uses: actions/upload-artifact@v3
        with:
          name: Lyra-Audio-Player
          path: app/build/outputs/apk/debug/app-debug.apk

